micronaut:
  application:
    name: product-catalog-micronaut-native
  metrics:
    enabled: true
    export:
      otlp:
        enabled: true
        uri: http://localhost:4317
        service-name: product-catalog-micronaut-native
    tags:
      application: ${micronaut.application.name}
      job: ${micronaut.application.name}
  otel:
    enabled: true

vertx:
  pg:
    host: ${POSTGRES_HOST:localhost}
    port: 5432
    database: product_catalog
    username: postgres
    password: postgres
    maxPoolSize: 10

otel:
  traces:
    exporter: otlp
  metrics:
    enabled: true
    exporter: otlp
  exporter:
    otlp:
      enabled: true
      protocol: http/protobuf
      endpoint: http://${OTEL_COLLECTOR_HOST:localhost}:${OTEL_COLLECTOR_PORT:4318}